name: thapo_site_data

networks:
  thapo_site_data_network:


services:

  static_server:
    image: "docker.io/nginx:1.28.0"
    restart: "no"
    ports:
      - "12089:12089"
    networks:
      - thapo_site_data_network
    volumes:
      - ./nginx/local.conf:/etc/nginx/conf.d/default.conf:ro
      - ../data:/html/data:ro
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "128M"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12089/data/blogs/blogs.json"]
      interval: 30s
      timeout: 10s
